### ISSUE TITLE
Update template - replace # with let

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [ScottMGerstl/ng2-validate#4]
Template parse warnings:
"#" inside of expressions is deprecated. Use "let" instead! ("
    <div *ngIf="messages" [ERROR ->]*ngFor="#message of messages">
        <validation-message *ngIf="message" [message]="message[message"): ValidationMessagesComponent@1:26

**Comment by ScottMGerstl** [comment]
You're right. I missed that during the upgrade. Thanks
