### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [ScottMGerstl/ng2-validate#5]
This looks like great lib but documentation doesn't follow :(

It would be nice if you update repo / wiki with more examples. 
Currently it took me ~ 2 hours to get into logic you are following :) 
For sure I'll more like this lib if I had few real world examples to look into it.

**Comment by ScottMGerstl** [comment]
Can you get into specifics about what is lacking? I documented my approach but I would love to get an understanding of how others want to use this!
